"""Generate one consolidated Sprint 1 output report."""

import csv
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPRINT1_OUTPUT = ROOT / "output" / "sprint1_completion_report.md"
SPRINT2_OUTPUT = ROOT / "output" / "sprint2_completion_report.md"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as source:
        return list(csv.DictReader(source))


def main() -> int:
    manifest = read_csv(ROOT / "source_manifest.csv")
    audit = read_csv(ROOT / "output" / "load_audit.csv")
    validation = read_csv(ROOT / "output" / "validation_failures.csv")
    test_run = subprocess.run([sys.executable, "-m", "pytest", "-q"], cwd=ROOT, capture_output=True, text=True)
    collection_run = subprocess.run([sys.executable, "-m", "pytest", "--collect-only", "-q"], cwd=ROOT, capture_output=True, text=True)
    collected = [int(value) for value in re.findall(r":\s+(\d+)\s*$", collection_run.stdout, re.MULTILINE)]
    test_count = sum(collected) if collected else "unknown"
    with sqlite3.connect(ROOT / "nifty100.db") as database:
        companies = database.execute("SELECT COUNT(*) FROM companies").fetchone()[0]
        foreign_keys = database.execute("PRAGMA foreign_key_check").fetchall()
        tables = database.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
        ratio_rows = database.execute("SELECT COUNT(*) FROM financial_ratios").fetchone()[0]
        ratio_columns = len(database.execute("PRAGMA table_info(financial_ratios)").fetchall())
        null_only = [row[1] for row in database.execute("PRAGMA table_info(financial_ratios)") if row[1] not in {"company_id", "year"} and database.execute(f"SELECT COUNT(*) FROM financial_ratios WHERE [{row[1]}] IS NOT NULL").fetchone()[0] == 0]
        screener = database.execute("""
            SELECT COUNT(*) FROM financial_ratios r
            WHERE r.year = (SELECT MAX(r2.year) FROM financial_ratios r2 WHERE r2.company_id = r.company_id AND r2.year <> 'TTM')
              AND r.return_on_equity_pct > 15 AND r.debt_to_equity < 1
        """).fetchone()[0]
    critical = sum(row["severity"] == "CRITICAL" for row in validation)
    sprint1 = [
        "# Sprint 1 Completion Report", "", "Generated by `scripts/generate_completion_report.py`.", "",
        "## Definition of Done", "", f"- Companies: **{companies}** (required: 92)",
        f"- Foreign-key errors: **{len(foreign_keys)}** (required: 0)", f"- Critical DQ failures: **{critical}** (required: 0)",
        f"- Tests collected: **{test_count}**", f"- Database tables: **{len(tables)}**", "",
        "## Source Manifest", "", "| Source file | Logical table | Status | Notes |", "|---|---|---|---|",
    ]
    sprint1.extend(f"| {row['source_file']} | {row['logical_table']} | {row['status']} | {row['notes']} |" for row in manifest)
    sprint1.extend(["", "## Load Audit", "", "| Table | Loaded rows | Rejected rows | Critical rejections |", "|---|---:|---:|---:|"])
    sprint1.extend(f"| {row['table']} | {row['rows']} | {row['rejected_rows']} | {row['critical_rejections']} |" for row in audit)
    sprint1.extend(["", "## Validation Summary", "", "| Rule | Severity | Findings |", "|---|---|---:|"])
    counts: dict[tuple[str, str], int] = {}
    for row in validation:
        key = (row["rule"], row["severity"])
        counts[key] = counts.get(key, 0) + 1
    sprint1.extend(f"| {rule} | {severity} | {count} |" for (rule, severity), count in sorted(counts.items()))
    sprint1.extend(["", "## Database Tables", "", *[f"- `{table[0]}`" for table in tables], ""])

    sprint2 = [
        "# Sprint 2 Completion Report", "", "Generated by `scripts/generate_completion_report.py`.", "",
        "## Ratio Engine Exit Criteria", "", f"- Financial ratio rows: **{ratio_rows}** (required: >= 1,100)",
        f"- Financial ratio columns: **{ratio_columns}**", f"- Null-only KPI columns: **{len(null_only)}** (required: 0)",
        f"- Latest-annual screener matches: **{screener}** (required: 15-50)",
        f"- Capital allocation output: **{'present' if (ROOT / 'output' / 'capital_allocation.csv').exists() else 'missing'}**",
        f"- Ratio edge-case log: **{'present' if (ROOT / 'output' / 'ratio_edge_cases.log').exists() else 'missing'}**", "",
        "## Test Evidence", "", f"- Test command exit code: **{test_run.returncode}**", f"- Tests collected: **{test_count}**", "", "```text", test_run.stdout.strip(), "```", "",
        "## Sprint 2 Artifacts", "", "- `src/analytics/ratios.py`", "- `src/analytics/cagr.py`", "- `src/analytics/cashflow_kpis.py`", "- `src/analytics/engine.py`", "- `output/capital_allocation.csv`", "- `output/ratio_edge_cases.log`", "- `tests/kpi/test_formula_kpis.py`", "",
    ]
    SPRINT1_OUTPUT.write_text("\n".join(sprint1), encoding="utf-8")
    SPRINT2_OUTPUT.write_text("\n".join(sprint2), encoding="utf-8")
    print(SPRINT1_OUTPUT)
    print(SPRINT2_OUTPUT)
    return 0 if test_run.returncode == 0 and not foreign_keys and critical == 0 and ratio_rows >= 1100 and not null_only and 15 <= screener <= 50 else 1


if __name__ == "__main__":
    raise SystemExit(main())
