"""Generate one consolidated Sprint 1 output report."""

import csv
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "output" / "sprint1_completion_report.md"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as source:
        return list(csv.DictReader(source))


def main() -> int:
    manifest = read_csv(ROOT / "source_manifest.csv")
    audit = read_csv(ROOT / "output" / "load_audit.csv")
    validation = read_csv(ROOT / "output" / "validation_failures.csv")
    test_run = subprocess.run([sys.executable, "-m", "pytest", "-q"], cwd=ROOT, capture_output=True, text=True)
    collection_run = subprocess.run([sys.executable, "-m", "pytest", "--collect-only", "-q"], cwd=ROOT, capture_output=True, text=True)
    collected = [int(value) for value in re.findall(r":\s+(\d+)\s*$", collection_run.stdout, re.MULTILINE)]
    test_count = sum(collected) if collected else "unknown"
    with sqlite3.connect(ROOT / "nifty100.db") as database:
        companies = database.execute("SELECT COUNT(*) FROM companies").fetchone()[0]
        foreign_keys = database.execute("PRAGMA foreign_key_check").fetchall()
        tables = database.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
    critical = sum(row["severity"] == "CRITICAL" for row in validation)
    lines = [
        "# Sprint 1 Completion Report", "", "Generated by `scripts/generate_completion_report.py`.", "",
        "## Definition of Done", "", f"- Companies: **{companies}** (required: 92)",
        f"- Foreign-key errors: **{len(foreign_keys)}** (required: 0)", f"- Critical DQ failures: **{critical}** (required: 0)",
        f"- Test command exit code: **{test_run.returncode}**", f"- Tests collected: **{test_count}**", f"- Database tables: **{len(tables)}**", "",
        "## Test Output", "", "```text", test_run.stdout.strip(), test_run.stderr.strip(), "```", "",
        "## Source Manifest", "", "| Source file | Logical table | Status | Notes |", "|---|---|---|---|",
    ]
    lines.extend(f"| {row['source_file']} | {row['logical_table']} | {row['status']} | {row['notes']} |" for row in manifest)
    lines.extend(["", "## Load Audit", "", "| Table | Loaded rows | Rejected rows | Critical rejections |", "|---|---:|---:|---:|"])
    lines.extend(f"| {row['table']} | {row['rows']} | {row['rejected_rows']} | {row['critical_rejections']} |" for row in audit)
    lines.extend(["", "## Validation Summary", "", "| Rule | Severity | Findings |", "|---|---|---:|"])
    counts: dict[tuple[str, str], int] = {}
    for row in validation:
        key = (row["rule"], row["severity"])
        counts[key] = counts.get(key, 0) + 1
    lines.extend(f"| {rule} | {severity} | {count} |" for (rule, severity), count in sorted(counts.items()))
    lines.extend(["", "## Database Tables", "", *[f"- `{table[0]}`" for table in tables], ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(OUTPUT)
    return 0 if test_run.returncode == 0 and not foreign_keys and critical == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
